# Generated by Django 5.0.8 on 2025-01-24 12:30
# Modified: Finca and Lote models were moved to fincas_app
# This migration is now a no-op because tables already exist
# -*- coding: utf-8 -*-

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_training_job'),
        ('fincas_app', '0001_initial'),  # Ensure fincas_app migrations run first
    ]

    operations = [
        # No operations - Finca and Lote models were moved to fincas_app
        # Tables already exist, so this migration does nothing
        migrations.RunSQL("SELECT 1;", reverse_sql="SELECT 1;"),
    ]
