# Generated by Django 4.2.7 on 2025-10-24 20:54
# Updated: Removed ExpiringToken deletion since it was never created (authtoken removed)

from django.db import migrations


def check_and_remove_expiring_token(apps, schema_editor):
    """
    Remove ExpiringToken only if it exists (for backward compatibility).
    Since authtoken was removed, ExpiringToken should not exist.
    """
    db_alias = schema_editor.connection.alias
    try:
        ExpiringToken = apps.get_model('api', 'ExpiringToken')
        ExpiringToken.objects.using(db_alias).all().delete()
    except LookupError:
        # Model doesn't exist, which is expected
        pass


def reverse_remove_expiring_token(apps, schema_editor):
    """
    Reverse operation - cannot recreate ExpiringToken without authtoken.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_fincas_lotes_models'),
    ]

    operations = [
        migrations.RunPython(
            check_and_remove_expiring_token,
            reverse_remove_expiring_token,
        ),
    ]


