# Generated by Django 4.2.7 on 2025-10-24 20:55
# Modified: Lote model was moved to fincas_app
# -*- coding: utf-8 -*-

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_expiring_token'),
        ('fincas_app', '0001_initial'),  # Ensure fincas_app migrations run first
    ]

    operations = [
        migrations.RemoveField(
            model_name='cacaoimage',
            name='lote_id',
        ),
        migrations.AddField(
            model_name='cacaoimage',
            name='lote',
            field=models.ForeignKey(blank=True, help_text='Lote al que pertenece esta imagen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cacao_images', to='fincas_app.lote'),
        ),
    ]


