# Generated by Django 4.2.7 on 2025-11-25 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_moved_models'),
    ]

    operations = [
        # ActivityLog was moved to audit app - only update state, don't touch database
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='activitylog',
                    name='usuario',
                ),
                migrations.DeleteModel(
                    name='ActivityLog',
                ),
            ],
            database_operations=[
                # Table is managed by audit app, don't modify it here
                migrations.RunSQL("SELECT 1;", reverse_sql="SELECT 1;"),
            ],
        ),
        # CacaoImage and CacaoPrediction were moved to images_app - only update state, don't touch database
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='cacaoimage',
                    name='lote',
                ),
                migrations.RemoveField(
                    model_name='cacaoimage',
                    name='user',
                ),
                migrations.DeleteModel(
                    name='CacaoImage',
                ),
                migrations.RemoveField(
                    model_name='cacaoprediction',
                    name='image',
                ),
                migrations.DeleteModel(
                    name='CacaoPrediction',
                ),
            ],
            database_operations=[
                # Tables are managed by images_app, don't modify them here
                migrations.RunSQL("SELECT 1;", reverse_sql="SELECT 1;"),
            ],
        ),
        # Finca and Lote were moved to fincas_app - only update state, don't touch database
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='finca',
                    name='agricultor',
                ),
                migrations.DeleteModel(
                    name='Finca',
                ),
                migrations.RemoveField(
                    model_name='lote',
                    name='finca',
                ),
                migrations.DeleteModel(
                    name='Lote',
                ),
            ],
            database_operations=[
                # Tables are managed by fincas_app, don't modify them here
                migrations.RunSQL("SELECT 1;", reverse_sql="SELECT 1;"),
            ],
        ),
        # LoginHistory was moved to audit app - only update state, don't touch database
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='loginhistory',
                    name='usuario',
                ),
                migrations.DeleteModel(
                    name='LoginHistory',
                ),
            ],
            database_operations=[
                # Table is managed by audit app, don't modify it here
                migrations.RunSQL("SELECT 1;", reverse_sql="SELECT 1;"),
            ],
        ),
        # ModelMetrics was moved to training app - only update state, don't touch database
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='modelmetrics',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='modelmetrics',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='modelmetrics',
                    name='training_job',
                ),
                migrations.DeleteModel(
                    name='ModelMetrics',
                ),
            ],
            database_operations=[
                # Table is managed by training app, don't modify it here
                migrations.RunSQL("SELECT 1;", reverse_sql="SELECT 1;"),
            ],
        ),
        # Notification was moved to notifications app - only update state, don't touch database
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='notification',
                    name='user',
                ),
                migrations.DeleteModel(
                    name='Notification',
                ),
            ],
            database_operations=[
                # Table is managed by notifications app, don't modify it here
                migrations.RunSQL("SELECT 1;", reverse_sql="SELECT 1;"),
            ],
        ),
        # ReporteGenerado was moved to reports app - only update state, don't touch database
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='reportegenerado',
                    name='usuario',
                ),
                migrations.DeleteModel(
                    name='ReporteGenerado',
                ),
            ],
            database_operations=[
                # Table is managed by reports app, don't modify it here
                migrations.RunSQL("SELECT 1;", reverse_sql="SELECT 1;"),
            ],
        ),
        # SystemSettings was moved to core app - only update state, don't touch database
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='SystemSettings',
                ),
            ],
            database_operations=[
                # Table is managed by core app, don't modify it here
                migrations.RunSQL("SELECT 1;", reverse_sql="SELECT 1;"),
            ],
        ),
        # TrainingJob was moved to training app - only update state, don't touch database
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='trainingjob',
                    name='created_by',
                ),
                migrations.DeleteModel(
                    name='TrainingJob',
                ),
            ],
            database_operations=[
                # Table is managed by training app, don't modify it here
                migrations.RunSQL("SELECT 1;", reverse_sql="SELECT 1;"),
            ],
        ),
        # EmailVerificationToken and UserProfile were moved to auth_app - only update state, don't touch database
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='emailverificationtoken',
                    name='user',
                ),
                migrations.DeleteModel(
                    name='EmailVerificationToken',
                ),
                migrations.RemoveField(
                    model_name='userprofile',
                    name='user',
                ),
                migrations.DeleteModel(
                    name='UserProfile',
                ),
            ],
            database_operations=[
                # Tables are managed by auth_app, don't modify them here
                migrations.RunSQL("SELECT 1;", reverse_sql="SELECT 1;"),
            ],
        ),
    ]
