# Generated by Django 5.2.9 on 2025-12-09 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_normalize_reportegenerado_catalogs'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reportegenerado',
            name='api_reportegenerado_tipo_reporte_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportegenerado',
            name='api_reportegenerado_formato_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportegenerado',
            name='api_reportegenerado_estado_idx',
        ),
    ]
