# Generated by Django 5.2.9 on 2025-12-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_remove_reportegenerado_api_reportegenerado_tipo_reporte_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportegenerado',
            name='filtros_aplicados',
            field=models.JSONField(blank=True, default=dict, help_text='Filtros aplicados al generar el reporte (JSON). Evitar duplicar datos que deberían ser ForeignKeys. Usar referencias por ID en lugar de objetos completos.'),
        ),
        migrations.AlterField(
            model_name='reportegenerado',
            name='parametros',
            field=models.JSONField(blank=True, default=dict, help_text='Parámetros adicionales del reporte (JSON). Evitar duplicar datos que deberían ser ForeignKeys (ej: IDs de fincas, municipios). Usar referencias por ID en lugar de objetos completos.'),
        ),
    ]
