# Generated by Django 5.2.9 on 2025-12-09 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0017_temaparametro_and_more'),
        ('reports', '0011_alter_reportegenerado_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportegenerado',
            name='estado',
            field=models.ForeignKey(help_text='Estado del reporte', limit_choices_to={'tema__codigo': 'TEMA_ESTADO_REPORTE'}, on_delete=django.db.models.deletion.PROTECT, related_name='reportes_estado', to='catalogos.parametro'),
        ),
        migrations.AlterField(
            model_name='reportegenerado',
            name='formato',
            field=models.ForeignKey(help_text='Formato del reporte', limit_choices_to={'tema__codigo': 'TEMA_FORMATO_REPORTE'}, on_delete=django.db.models.deletion.PROTECT, related_name='reportes_formato', to='catalogos.parametro'),
        ),
        migrations.AlterField(
            model_name='reportegenerado',
            name='tipo_reporte',
            field=models.ForeignKey(help_text='Tipo de reporte', limit_choices_to={'tema__codigo': 'TEMA_TIPO_REPORTE'}, on_delete=django.db.models.deletion.PROTECT, related_name='reportes_tipo', to='catalogos.parametro'),
        ),
    ]
