# Generated by Django 5.2.9 on 2025-12-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_normalize_notification_tipo'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificati_tipo_id_idx',
        ),
    ]
