# Generated by Django 5.2.9 on 2025-12-09 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0017_temaparametro_and_more'),
        ('notifications', '0008_alter_notification_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='tipo',
            field=models.ForeignKey(help_text='Tipo de notificación (normalizado con catálogo)', limit_choices_to={'tema__codigo': 'TEMA_TIPO_NOTIFICACION'}, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='catalogos.parametro'),
        ),
    ]
