# Generated by Django 5.2.9 on 2025-12-09 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_add_string_defaults'),
        ('fincas_app', '0010_remove_lote_fincas_app_lote_identificador_unico_por_finca_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='finca',
            name='api_finca_municip_582e68_idx',
        ),
        migrations.RemoveField(
            model_name='finca',
            name='departamento',
        ),
        migrations.AlterField(
            model_name='finca',
            name='municipio',
            field=models.ForeignKey(help_text='Municipio donde se encuentra la finca', on_delete=django.db.models.deletion.PROTECT, related_name='fincas', to='catalogos.municipio'),
        ),
        migrations.AddIndex(
            model_name='finca',
            index=models.Index(fields=['municipio'], name='api_finca_municip_43980f_idx'),
        ),
    ]
