# Generated by Django 5.2.9 on 2025-12-09 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fincas_app', '0017_merge_0015_remove_indexes_and_table'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='finca',
            name='api_finca_agricul_8d1606_idx',
        ),
        migrations.RemoveIndex(
            model_name='finca',
            name='api_finca_municip_43980f_idx',
        ),
        migrations.RemoveIndex(
            model_name='finca',
            name='api_finca_estado__63f86d_idx',
        ),
        migrations.RemoveIndex(
            model_name='finca',
            name='api_finca_tipo_su_e9b000_idx',
        ),
        migrations.RemoveIndex(
            model_name='finca',
            name='api_finca_clima_i_f6ba0a_idx',
        ),
    ]
