# Generated by Django 5.2.9 on 2025-12-09 21:46
# Modified: This migration was auto-generated but is redundant because
# migrations 0020 and 0021 already migrated these fields to catalogos.parametro.
# Converting to no-op to avoid errors with non-existent catalog tables.
# -*- coding: utf-8 -*-

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0014_remove_old_catalog_tables'),
        ('fincas_app', '0021_migrate_lote_catalogs_to_parametros'),
    ]

    operations = [
        # No-op: Fields were already migrated to catalogos.parametro in migrations 0020 and 0021
        # This migration was auto-generated but would try to alter fields to point to
        # non-existent catalog tables (catalogos.clima, catalogos.estadofinca, etc.)
        migrations.RunSQL(
            sql="SELECT 1;",  # No-op SQL
            reverse_sql="SELECT 1;"  # No-op SQL
        ),
    ]
