# Generated by Django 5.2.9 on 2025-12-09 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0017_temaparametro_and_more'),
        ('fincas_app', '0022_alter_finca_clima_alter_finca_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finca',
            name='clima',
            field=models.ForeignKey(blank=True, help_text='Tipo de clima de la finca', limit_choices_to={'tema__codigo': 'TEMA_CLIMA'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fincas_clima', to='catalogos.parametro'),
        ),
        migrations.AlterField(
            model_name='finca',
            name='estado',
            field=models.ForeignKey(blank=True, help_text='Estado de la finca', limit_choices_to={'tema__codigo': 'TEMA_ESTADO_FINCA'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fincas_estado', to='catalogos.parametro'),
        ),
        migrations.AlterField(
            model_name='finca',
            name='tipo_suelo',
            field=models.ForeignKey(blank=True, help_text='Tipo de suelo de la finca', limit_choices_to={'tema__codigo': 'TEMA_TIPO_SUELO'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fincas_tipo_suelo', to='catalogos.parametro'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='estado',
            field=models.ForeignKey(blank=True, help_text='Estado actual del lote', limit_choices_to={'tema__codigo': 'TEMA_ESTADO_LOTE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_estado', to='catalogos.parametro'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='variedad',
            field=models.ForeignKey(help_text='Variedad de cacao del lote', limit_choices_to={'tema__codigo': 'TEMA_VARIEDAD_CACAO'}, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_variedad', to='catalogos.parametro'),
        ),
    ]
