# Generated by Django 5.2.9 on 2025-12-09 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_add_userprofile_string_defaults'),
        ('catalogos', '0003_add_string_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='farm_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='municipality',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='region',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='municipio',
            field=models.ForeignKey(blank=True, help_text='Municipio de residencia del usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='catalogos.municipio'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['municipio'], name='auth_app_us_municip_97842b_idx'),
        ),
    ]
