# Generated by Django 5.2.9 on 2025-12-09 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_remove_duplicate_municipio_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userprofile',
            name='auth_app_us_municip_97842b_idx',
        ),
    ]
