# Generated by Django 5.2.9 on 2025-12-09 21:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_remove_userprofile_auth_app_us_municip_97842b_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email a verificar', max_length=254)),
                ('verification_type', models.CharField(choices=[('registration', 'Registro'), ('password_reset', 'Recuperación de contraseña'), ('email_change', 'Cambio de email'), ('otp', 'OTP')], default='registration', help_text='Tipo de verificación', max_length=20)),
                ('token', models.UUIDField(blank=True, default=uuid.uuid4, help_text='Token UUID para verificación por enlace', null=True, unique=True)),
                ('otp_code', models.CharField(blank=True, help_text='Código OTP de 6 dígitos', max_length=6, null=True)),
                ('temp_data', models.JSONField(blank=True, default=dict, help_text='Datos temporales (ej: datos de pre-registro)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('last_sent', models.DateTimeField(auto_now=True, help_text='Última vez que se envió el código/token')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Fecha de verificación', null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Indica si ya fue verificado')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario existente (solo para verificación de usuarios registrados)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verificación de Email',
                'verbose_name_plural': 'Verificaciones de Email',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='emailverificationtoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='PendingEmailVerification',
        ),
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['email', 'verification_type'], name='auth_app_em_email_21985f_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['token'], name='auth_app_em_token_f795af_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['email', 'otp_code'], name='auth_app_em_email_e20170_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['is_verified', 'created_at'], name='auth_app_em_is_veri_bf2951_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['user'], name='auth_app_em_user_id_367897_idx'),
        ),
    ]
