# Generated by Django 5.2.9 on 2025-12-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_add_normalization_catalogs'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clima',
            new_name='catalogos_c_codigo_2169bb_idx',
            old_name='catalogos_clima_codigo_idx',
        ),
        migrations.RenameIndex(
            model_name='clima',
            new_name='catalogos_c_activo_fccb52_idx',
            old_name='catalogos_clima_activo_idx',
        ),
        migrations.RenameIndex(
            model_name='estadofinca',
            new_name='catalogos_e_codigo_eb1838_idx',
            old_name='catalogos_estadofinca_codigo_idx',
        ),
        migrations.RenameIndex(
            model_name='estadofinca',
            new_name='catalogos_e_activo_a62a0e_idx',
            old_name='catalogos_estadofinca_activo_idx',
        ),
        migrations.RenameIndex(
            model_name='estadolote',
            new_name='catalogos_e_codigo_f6c12c_idx',
            old_name='catalogos_estadolote_codigo_idx',
        ),
        migrations.RenameIndex(
            model_name='estadolote',
            new_name='catalogos_e_activo_003f36_idx',
            old_name='catalogos_estadolote_activo_idx',
        ),
        migrations.RenameIndex(
            model_name='tiposuelo',
            new_name='catalogos_t_codigo_ac46d9_idx',
            old_name='catalogos_tiposuelo_codigo_idx',
        ),
        migrations.RenameIndex(
            model_name='tiposuelo',
            new_name='catalogos_t_activo_b2989e_idx',
            old_name='catalogos_tiposuelo_activo_idx',
        ),
        migrations.RenameIndex(
            model_name='variedadcacao',
            new_name='catalogos_v_codigo_4c4af4_idx',
            old_name='catalogos_variedadcacao_codigo_idx',
        ),
        migrations.RenameIndex(
            model_name='variedadcacao',
            new_name='catalogos_v_activo_05dd22_idx',
            old_name='catalogos_variedadcacao_activo_idx',
        ),
    ]
