# Generated by Django 5.2.9 on 2025-12-09 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_add_report_catalogs'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='estadoreporte',
            new_name='catalogos_e_codigo_45aae3_idx',
            old_name='catalogos_estadoreporte_codigo_idx',
        ),
        migrations.RenameIndex(
            model_name='estadoreporte',
            new_name='catalogos_e_activo_d1360e_idx',
            old_name='catalogos_estadoreporte_activo_idx',
        ),
        migrations.RenameIndex(
            model_name='formatoreporte',
            new_name='catalogos_f_codigo_803b0a_idx',
            old_name='catalogos_formatoreporte_codigo_idx',
        ),
        migrations.RenameIndex(
            model_name='formatoreporte',
            new_name='catalogos_f_activo_0aa44d_idx',
            old_name='catalogos_formatoreporte_activo_idx',
        ),
        migrations.RenameIndex(
            model_name='tiporeporte',
            new_name='catalogos_t_codigo_8e47c2_idx',
            old_name='catalogos_tiporeporte_codigo_idx',
        ),
        migrations.RenameIndex(
            model_name='tiporeporte',
            new_name='catalogos_t_activo_ef2c63_idx',
            old_name='catalogos_tiporeporte_activo_idx',
        ),
    ]
