# Generated by Django 5.2.9 on 2025-12-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0008_add_tipo_notificacion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tiponotificacion',
            new_name='catalogos_t_codigo_62be96_idx',
            old_name='catalogos_t_codigo_8a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='tiponotificacion',
            new_name='catalogos_t_activo_7926b8_idx',
            old_name='catalogos_t_activo_3d4e5f_idx',
        ),
    ]
