# Generated by Django 5.2.9 on 2025-12-09 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0011_add_ml_catalogs'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tipoarchivo',
            new_name='catalogos_t_codigo_aeb37b_idx',
            old_name='catalogos_t_codigo_archivo_idx',
        ),
        migrations.RenameIndex(
            model_name='tipoarchivo',
            new_name='catalogos_t_mime_ty_52e0b0_idx',
            old_name='catalogos_t_mime_type_idx',
        ),
        migrations.RenameIndex(
            model_name='tipoarchivo',
            new_name='catalogos_t_activo_7d6c5c_idx',
            old_name='catalogos_t_activo_archivo_idx',
        ),
        migrations.RenameIndex(
            model_name='tipodispositivo',
            new_name='catalogos_t_codigo_6807c3_idx',
            old_name='catalogos_t_codigo_disp_idx',
        ),
        migrations.RenameIndex(
            model_name='tipodispositivo',
            new_name='catalogos_t_activo_af81e5_idx',
            old_name='catalogos_t_activo_disp_idx',
        ),
        migrations.RenameIndex(
            model_name='versionmodelo',
            new_name='catalogos_v_codigo_6169c7_idx',
            old_name='catalogos_v_codigo_vers_idx',
        ),
        migrations.RenameIndex(
            model_name='versionmodelo',
            new_name='catalogos_v_activo_d1852f_idx',
            old_name='catalogos_v_activo_vers_idx',
        ),
    ]
