# Generated by Django 5.2.9 on 2025-12-09 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0016_add_tema_foreignkey_to_parametro'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemaParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Relación Tema-Parámetro',
                'verbose_name_plural': 'Relaciones Tema-Parámetro',
            },
        ),
        migrations.RemoveIndex(
            model_name='parametro',
            name='catalogos_p_tema_id_codigo_idx',
        ),
        migrations.AddField(
            model_name='temaparametro',
            name='parametro',
            field=models.ForeignKey(help_text='Parámetro de la relación', on_delete=django.db.models.deletion.CASCADE, related_name='tema_parametro_set', to='catalogos.parametro'),
        ),
        migrations.AddField(
            model_name='temaparametro',
            name='tema',
            field=models.ForeignKey(help_text='Tema de la relación', on_delete=django.db.models.deletion.CASCADE, related_name='tema_parametro_set', to='catalogos.tema'),
        ),
        migrations.AddIndex(
            model_name='temaparametro',
            index=models.Index(fields=['tema', 'parametro'], name='catalogos_t_tema_id_85e5ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='temaparametro',
            unique_together={('tema', 'parametro')},
        ),
    ]
