apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: app-namespace
type: Opaque
stringData:
  DB_NAME: "cacaoscan_db"
  DB_USER: "postgres"
  DB_PASSWORD: "CHANGE_THIS_PASSWORD"
  SECRET_KEY: "CHANGE_THIS_SECRET_KEY"

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: app-namespace
type: Opaque
stringData:
  POSTGRES_DB: "cacaoscan_db"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "CHANGE_THIS_PASSWORD"

