# Generated by Django 5.2.9 on 2025-12-09 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fincas_app', '0011_remove_finca_api_finca_municip_582e68_idx_and_more'),
        ('images_app', '0005_cacaoprediction_analysis_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cacaoimage',
            name='images_app__region_efbff0_idx',
        ),
        migrations.RemoveField(
            model_name='cacaoimage',
            name='fecha_cosecha',
        ),
        migrations.RemoveField(
            model_name='cacaoimage',
            name='finca_nombre',
        ),
        migrations.RemoveField(
            model_name='cacaoimage',
            name='region',
        ),
        migrations.RemoveField(
            model_name='cacaoimage',
            name='variedad',
        ),
        migrations.AddIndex(
            model_name='cacaoimage',
            index=models.Index(fields=['finca'], name='images_app__finca_i_850928_idx'),
        ),
        migrations.AddIndex(
            model_name='cacaoimage',
            index=models.Index(fields=['lote'], name='images_app__lote_id_6c0fd1_idx'),
        ),
    ]
