# Generated by Django 5.2.9 on 2025-12-09 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fincas_app', '0013_normalize_lote_catalogos'),
        ('images_app', '0007_remove_finca_redundancy'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cacaoimage',
            name='images_app__finca_i_850928_idx',
        ),
        migrations.AlterField(
            model_name='cacaoimage',
            name='lote',
            field=models.ForeignKey(blank=True, help_text='Lote al que pertenece esta imagen (la finca se obtiene de lote.finca)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cacao_images', to='fincas_app.lote'),
        ),
    ]
