# Generated by Django 5.2.9 on 2025-12-09 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images_app', '0012_normalize_prediction_ml_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cacaoprediction',
            name='images_app__model_v_d66094_idx',
        ),
    ]
