# Generated by Django 5.2.9 on 2025-12-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_app', '0013_remove_cacaoprediction_images_app__model_v_d66094_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacaoimage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata adicional en formato JSON. Evitar duplicar datos que deberían ser ForeignKeys o campos normalizados. Usar solo para datos verdaderamente flexibles y no estructurados.'),
        ),
    ]
