# Generated by Django 5.2.9 on 2025-12-09 21:46
# Modified: This migration was auto-generated but is redundant because
# migration 0013_migrate_image_catalogs_to_parametros already migrated these fields to catalogos.parametro.
# Converting to no-op to avoid errors with non-existent catalog tables.
# -*- coding: utf-8 -*-

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0014_remove_old_catalog_tables'),
        ('images_app', '0015_merge_0013_migrate_and_remove'),
    ]

    operations = [
        # No-op: Fields were already migrated to catalogos.parametro in migration 0013_migrate_image_catalogs_to_parametros
        # This migration was auto-generated but would try to alter fields to point to
        # non-existent catalog tables (catalogos.tipoarchivo, catalogos.tipodispositivo, catalogos.versionmodelo)
        migrations.RunSQL(
            sql="SELECT 1;",  # No-op SQL
            reverse_sql="SELECT 1;"  # No-op SQL
        ),
    ]
