# Generated by Django 5.2.9 on 2025-12-09 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0017_temaparametro_and_more'),
        ('images_app', '0016_alter_cacaoimage_file_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacaoimage',
            name='file_type',
            field=models.ForeignKey(blank=True, help_text='Tipo de archivo (normalizado)', limit_choices_to={'tema__codigo': 'TEMA_TIPO_ARCHIVO'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cacao_images', to='catalogos.parametro'),
        ),
        migrations.AlterField(
            model_name='cacaoprediction',
            name='device_used',
            field=models.ForeignKey(help_text='Dispositivo usado para procesamiento (normalizado)', limit_choices_to={'tema__codigo': 'TEMA_TIPO_DISPOSITIVO'}, on_delete=django.db.models.deletion.PROTECT, related_name='predictions_device_used', to='catalogos.parametro'),
        ),
        migrations.AlterField(
            model_name='cacaoprediction',
            name='model_version',
            field=models.ForeignKey(help_text='Versión del modelo usado (normalizado)', limit_choices_to={'tema__codigo': 'TEMA_VERSION_MODELO'}, on_delete=django.db.models.deletion.PROTECT, related_name='predictions_model_version', to='catalogos.parametro'),
        ),
    ]
