# Generated by Django 5.2.9 on 2025-12-09 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0007_rename_catalogos_estadoreporte_codigo_idx_catalogos_e_codigo_45aae3_idx_and_more'),
        ('personas', '0009_remove_departamento_transitive_dependency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='municipio',
            field=models.ForeignKey(blank=True, help_text='Municipio de residencia (el departamento se obtiene de municipio.departamento)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas', to='catalogos.municipio'),
        ),
    ]
