# Generated by Django 5.2.9 on 2025-12-09 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0012_remove_explicit_duplicate_indexes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingRegistration',
        ),
    ]
