# Generated by Django 5.2.9 on 2025-12-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0009_normalize_activitylog_contenttype'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='api_activit_content_e169d7_idx',
            old_name='api_activity_content_idx',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='resource_id',
            field=models.IntegerField(blank=True, help_text='[DEPRECATED] ID del recurso afectado - usar object_id', null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='resource_type',
            field=models.CharField(blank=True, default='', help_text='[DEPRECATED] Tipo de recurso afectado - usar content_type', max_length=50),
        ),
    ]
