# Generated by Django 5.2.9 on 2025-12-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0012_add_activitylog_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='resource_id',
            field=models.IntegerField(blank=True, help_text='[DEPRECATED] ID del recurso afectado - usar object_id. Requiere resource_type si se proporciona.', null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='resource_type',
            field=models.CharField(blank=True, default='', help_text="[DEPRECATED] Tipo de recurso afectado - usar content_type. Debe ser un nombre de modelo válido (ej: 'CacaoImage', 'images_app.cacaoimage')", max_length=50),
        ),
    ]
